---
title: ensure_futureを使用する際の情報の欠落（Python）
type: troubleshooting
tags:
  - Agents
  - Python agent
  - Troubleshooting
metaDescription: 'If your Python application doesn''t report data after a few minutes, try these troubleshooting steps.'
freshnessValidatedDate: never
translationType: machine
---

## 問題

コルーチンで`asyncio.ensure_future`を使用する場合、詳細な関数トレース情報は表示されません。

## 解決

`ensure_future`から作成された Future は、作成されたのと同じコルーチンで待機する必要があります。 たとえば、 <DNT>**Before**</DNT>セクションでは、 `await`が`ensure_future`と共に存在しないため、情報が欠落することになります。

前です。

```
import asyncio

async def foo():
  ensure_future(bar())

async def bar():
  await asyncio.sleep(0.5)
```

後です。

```
import asyncio

async def foo():
  await ensure_future(bar())

async def bar():
  await asyncio.sleep(0.5)
```
