---
title: record_exception (API do agente Python)
type: apiDoc
shortDescription: Registra detalhes de uma exceção Python como um erro.
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: This call records the details of a Python exception as an error.'
freshnessValidatedDate: never
translationType: machine
---

## Sintaxe

```py
newrelic.agent.record_exception(exc=None, value=None, tb=None, params={}, ignore_errors=[], application=None)
```

Esta API foi descontinuada. Por favor use [`notice_error()`](/docs/agents/python-agent/python-agent-api/notice_error).

## Descrição

Registra detalhes de uma exceção Python como um erro.

Por padrão, o agente Python relata apenas exceções não tratadas. Use `record_exception` para registrar qualquer exceção do Python como um erro, que pode ser encontrado na interface do New Relic. Se nenhum parâmetro for fornecido, os detalhes da exceção que está sendo tratada no momento serão usados.

Você pode registrar até cinco exceções distintas por [transação](/docs/accounts-partnerships/education/getting-started-new-relic/glossary#transaction) e até 20 exceções no total em todas as transações por [ciclo de coleta](/docs/apm/new-relic-apm/getting-started/glossary#harvest-cycle).

Quando `record_exception()` é chamado no contexto de uma solicitação da Web de monitoramento ou de uma tarefa em segundo plano, os detalhes da exceção serão relatados no aplicativo ao qual a solicitação ou tarefa está sendo relatada.

Se chamada fora do contexto de uma solicitação da Web de monitoramento ou de uma tarefa em segundo plano, a chamada será ignorada, a menos que o argumento da palavra-chave [`application`](/docs/agents/python-agent/python-agent-api/application) seja fornecido e um objeto de aplicativo correspondente ao aplicativo no qual a exceção deve ser registrada seja fornecido. Um objeto de aplicativo adequado pode ser obtido usando a função `newrelic.agent.application()` .

## Parâmetro

<Callout variant="tip">
  Em quase todos os casos, `record_exception` não exigirá nenhum parâmetro.
</Callout>

<table>
  <thead>
    <tr>
      <th width="25%">
        Parâmetro
      </th>

      <th>
        Descrição
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `exc`

        _objeto de classe_
      </td>

      <td>
        Opcional e raramente usado. O tipo de exceção que está sendo tratada (um objeto de classe). Um dos três valores (`exc`, `value` e `tb`) retornados de [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info). Se você quiser passar qualquer um desses parâmetros, todos os três devem ser definidos e não podem ser definidos como `None`. Se você passar apenas um desses valores, a chamada não funcionará.
      </td>
    </tr>

    <tr>
      <td>
        `value`

        _int, string, outro_
      </td>

      <td>
        Opcional e raramente usado. O parâmetro de exceção. Um dos três valores (`exc`, `value` e `tb`) retornados de [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info). Se você quiser passar qualquer um desses parâmetros, todos os três devem ser definidos e não podem ser definidos como `None`. Se você passar apenas um desses valores, a chamada não funcionará.
      </td>
    </tr>

    <tr>
      <td>
        `tb`

        _objeto_
      </td>

      <td>
        Opcional e raramente usado. Um objeto traceback que encapsula a stack de chamadas no ponto onde ocorreu originalmente a exceção. Um dos três valores (`exc`, `value` e `tb`) retornados de [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info). Se você quiser passar qualquer um desses parâmetros, todos os três devem ser definidos e não podem ser definidos como `None`. Se você passar apenas um desses valores, a chamada não funcionará.
      </td>
    </tr>

    <tr>
      <td>
        `params`

        _dict_
      </td>

      <td>
        Opcional. atributo personalizado a ser adicionado ao evento de erro (além de qualquer atributo personalizado já adicionado à transação). Se [o modo de alta segurança](/docs/agents/manage-apm-agents/configuration/high-security-mode) estiver ativado, isso não funcionará.
      </td>
    </tr>

    <tr>
      <td>
        `ignore_errors`

        _corda_
      </td>

      <td>
        Opcional. Erros a serem ignorados podem ser passados no formato `module:class`. Útil quando certos tipos de exceções sempre devem ser ignorados e nunca registrados.
      </td>
    </tr>

    <tr>
      <td>
        `application`

        _objeto de aplicativo_
      </td>

      <td>
        Opcional. Se chamada fora do contexto de uma solicitação da Web de monitoramento ou de uma tarefa em segundo plano, a chamada será ignorada, a menos que o [objeto`application` ](/docs/agents/python-agent/python-agent-api/application)seja fornecido.
      </td>
    </tr>
  </tbody>
</table>

## Valores de retorno

Nenhum.

## Exemplos

### Exemplo simples de reportar exceções [#simple-example]

Na grande maioria dos casos, você não precisará passar nenhum parâmetro. Você apenas chamaria o seguinte quando quiser relatar uma exceção:

```py
newrelic.agent.record_exception()
```

### Chame com tupla sys.exc_info() e parâmetro adicional [#complex-example]

Um exemplo de `record_exception` usando dados `sys.exc_info()` :

```py
def complex_ignore_errors(exc, val, tb):
   # do some logic here
   return False

newrelic.agent.record_exception(params={'my_special_exception': True}, ignore_errors=complex_ignore_errors)
```

### Exemplo usando retorno de chamada [#callback-example]

Se precisar filtrar exceções dinamicamente com base no atributo de um tipo de exceção específico, você pode fornecer uma função de retorno de chamada:

```py
def _ignore_errors(exc, value, tb): 
    if instance(value, HTTPError): 
        if value.status == 404: 
            return True

newrelic.agent.record_exception(ignore_errors=_ignore_errors)
```

Se a exceção for ignorada, defina o valor de retorno do chamável como `True`. Retorne `False` se a exceção nunca deve ser ignorada, independentemente de quaisquer outras verificações, e `None` se verificações subsequentes e regras integradas devem determinar se a exceção deve ser ignorada. Um retorno de chamada normalmente retornaria `True` ou `None`.
