---
title: Informations manquantes lors de l'utilisation de ensure_future (Python)
type: troubleshooting
tags:
  - Agents
  - Python agent
  - Troubleshooting
metaDescription: 'If your Python application doesn''t report data after a few minutes, try these troubleshooting steps.'
freshnessValidatedDate: never
translationType: machine
---

## Problème

Les informations détaillées sur la trace des fonctions n&apos;apparaissent pas lors de l&apos;utilisation `asyncio.ensure_future` dans les coroutines.

## Solution

Les futurs créés à partir de `ensure_future` doivent être attendus dans la même coroutine dans laquelle ils ont été créés. Par exemple, dans la section <DNT>**Before**</DNT> , `await` n&apos;est pas présent avec `ensure_future`, ce qui entraînerait des informations manquantes :

Avant:

```py
import asyncio

async def foo():
  ensure_future(bar())

async def bar():
  await asyncio.sleep(0.5)
```

Après:

```py
import asyncio

async def foo():
  await ensure_future(bar())

async def bar():
  await asyncio.sleep(0.5)
```