---
title: パイソンエージェントとセロリ
tags:
  - Agents
  - Python agent
  - Back-end services
metaDescription: How to record Celery background processes using the Python agent.
translationType: machine
---

Celery を分散タスク キューイング システムとして使用している場合は、Python エージェントを使用して、Celery プロセスを [非 Web トランザクション](/docs/apm/transactions/intro-transactions/monitor-background-processes-other-non-web-transactions)として記録できます。

Celery で Python エージェントを動作させるには、まず [エージェントのインストール手順](/docs/agents/python-agent/installation-and-configuration/python-agent-installation) に従って、エージェントのインストール、設定、 [テスト](/docs/agents/python-agent/installation-and-configuration/testing-python-agent) を行います。その後、以下のCelery固有の手順を使用します。

## ラン・セロリ [#running-with-celery]

エージェントでCeleryを実行するために使用するコマンドは、Celeryのバージョンと特定のセットアップによって異なります。

<CollapserGroup>
  <Collapser
    id="run-celery-celery"
    title="セロリ"
  >
    `celery`コマンドを使用する場合は、カスタムオプションを含めます。

    ```
    NEW_RELIC_CONFIG_FILE=/some/path/newrelic.ini newrelic-admin run-program celery YOUR_COMMAND_OPTIONS
    ```

    例えば：

    ```
    NEW_RELIC_CONFIG_FILE=/some/path/newrelic.ini newrelic-admin run-program celery -A tasks worker --loglevel=info
    ```
  </Collapser>

  <Collapser
    id="run-celery-celeryd"
    title="Celeryd"
  >
    `celeryd` runコマンドは、新しいCeleryリリースでは非推奨になっています。それでも`celeryd`を使用する場合は、カスタムオプションを含めます。

    ```
    NEW_RELIC_CONFIG_FILE=some/path/newrelic.ini newrelic-admin run-program celeryd YOUR_COMMAND_OPTIONS
    ```
  </Collapser>

  <Collapser
    id="run-celery-django"
    title="Django"
  >
    Django管理コマンドでCeleryを起動する場合は、 `manage.py`を使用してください。 `celery`コマンドをDjangoコマンドに置き換え、カスタムオプションを含めます。

    ```
    NEW_RELIC_CONFIG_FILE=/some/path/newrelic.ini newrelic-admin run-program python manage.py celery YOUR_COMMAND_OPTIONS
    ```
  </Collapser>

  <Collapser
    id="run-celery-initd"
    title="Initスクリプト"
  >
    Celery の汎用 init スクリプトのいずれかを使用している場合は、スクリプトを編集して、スクリプトの使用時に呼び出される `celery` コマンドをラップします。通常、このコマンドは次のようになります。

    ```
    CELERY_BIN=${CELERY_BIN:-"celery"}
    ```

    エージェントのラッパー スクリプトを追加するには、 `CELERY_BIN` 変数を次のように変更します。ここで、 `some/path/` はファイルまたはパッケージへの実際のパスです:

    ```
    CELERY_BIN=${CELERY_BIN:-"NEW_RELIC_CONFIG_FILE=/some/path/newrelic.ini /some/path/bin/newrelic-admin run-program /some/path/bin/celery"}
    ```

    この変更により、 `CELERY_BIN`が呼び出されるたびに、実際の`celery`コマンドの周りのエージェントラッパースクリプトで呼び出されます。
  </Collapser>
</CollapserGroup>

## アプリケーション名の選択 [#selecting-the-application-name]

Pythonエージェント構成ファイルの`app_name`設定は、NewRelicUIに表示されるアプリ名を設定します。

* PythonエージェントがCeleryタスクを監視し、 `app_name`をアプリケーションエージェントの`app_name`で使用されているのと同じ値に設定した場合、両方のソースからのデータがその名前でUIに結合されます。
* 異なる名前を設定した場合、データは2つの異なる名前としてUIに別々に表示されます。

[エージェントの設定ファイルに複数のアプリ名を設定することで](/docs/agents/manage-apm-agents/app-naming/use-multiple-names-app) 、結合されたデータと分離されたデータの両方を監視することができます。ここでは、Django アプリケーションを例に、一般的な方法を紹介します。

<CollapserGroup>
  <Collapser
    id="multiple-app-names"
    title="複数のアプリケーション名の使用"
  >
    Djangoアプリを監視するエージェントには、次のように設定します。

    ```
    app_name = Your_app_name (Django); Your_app_name (Combined)
    ```

    Celeryを監視するエージェントには、次のように設定します。

    ```
    app_name = Your_app_name (Celery); Your_app_name (Combined)
    ```

    この結果、UIには3つの名前が表示されます。

    * `Your_app_name (Combined)`、CeleryとDjangoアプリケーションの両方からのデータを組み合わせます
    * `Your_app_name (Django)`、Djangoアプリのデータを表示します
    * `Your_app_name (Celery)`、Celeryデータを表示します
  </Collapser>
</CollapserGroup>

## タスク・リトライ・エラーの無視 [#ignoring-task-retry-errors]

Celeryを使用している場合、タスクが失敗し、 `celery.exceptions:Retry`または`celery.exceptions:RetryTaskError`例外が発生する可能性があります。例外は、使用されているCeleryのバージョンによって異なります。

これらのエラーを無視するには、NewRelicApplication**設定**UIまたはエージェント構成ファイルからこれを設定します。 UIの変更は、構成の [優先順位ルールに従って構成](/docs/agents/python-agent/installation-configuration/python-agent-configuration#options)ファイルの変更をオーバーライドします。

エラーを無視する設定をUIから使用するため。

1. **[one.newrelic.com](https://one.newrelic.com/all-capabilities)**から、\[ **APM] > (アプリを選択) > \[設定] > \[アプリケーション] を選択します**。
2. 選択 **サーバーサイドエージェントの構成**.
3. **エラーコレクション** から、無視したいエラーをカンマで区切って入力します。

エージェント構成ファイルを使用してこれらのエラーを無視するには、 [`ignore_errors`](/docs/agents/python-agent/installation-configuration/python-agent-configuration#error-ignore)設定とスペースで区切られた例外のリストを使用します。

```
error_collector.ignore_errors = celery.exceptions:Retry celery.exceptions:RetryTaskError
```

## トラブルシューティング

Celeryワーカープロセスが突然終了すると、エージェントは通常のシャットダウンプロセスを完了することができず、最終的なデータペイロードが送信されません。その結果、エージェントから報告されるCeleryトランザクションの数が予想より少なくなるか、トランザクションが全く報告されなくなります。

これは、プールワーカープロセスが新しいタスクに置き換えられる前に実行できるタスクの最大数を定義する`CELERYD_MAX_TASKS_PER_CHILD`設定を使用している場合に発生する可能性があります。使用する場合、その制限に達するとワーカーは強制的にシャットダウンされます。これは、データがエージェントによって記録されないことを意味します。たとえば、 `MAX_TASKS_PER_CHILD = 1`の場合、これによりデータは報告されません。

これをトラブルシューティングする方法は、アプリケーションで`MAX_TASKS_PER_CHILD`制限を使用する理由によって異なります。

* 通常のシャットダウンプロセスを許可するには、これをデフォルトのノーリミット設定に戻します。
* 問題の影響を軽減するには、 `MAX_TASKS_PER_CHILD`の制限を引き上げます。

<Callout variant="important">
  バージョン3.2.2.94以降では、 `MAX_TASKS_PER_CHILD`の制限に達するとPythonエージェントがシャットダウンします。データが失われることはありません。
</Callout>

<Callout variant="important">
  Celery のメイン プロセスをエージェントで監視することはできません。ワーカー プロセスのみを監視できます。 [アクティブ化アプリケーションの警告を](/docs/apm/agents/python-agent/troubleshooting/activate-application-warning-python)参照してください
</Callout>