---
title: Missing information when using ensure_future (Python)
type: troubleshooting
tags:
  - Agents
  - Python agent
  - Troubleshooting
metaDescription: 'If your Python application doesn''t report data after a few minutes, try these troubleshooting steps.'
redirects:
  - /docs/agents/python-agent/troubleshooting/missing-information-when-using-ensurefuture-python
  - /docs/agents/python-agent/troubleshooting/information-missing-when-using-ensurefuture-python
freshnessValidatedDate: never
---

## Problem

Detailed function trace information does not appear when using `asyncio.ensure_future` in coroutines.

## Solution

Futures created from `ensure_future` must be awaited in the same coroutine in which they've been created. For example,in the <DNT>**Before**</DNT> section, `await` is not present with `ensure_future`, which would result in missing information:

Before:

```
import asyncio

async def foo():
  ensure_future(bar())

async def bar():
  await asyncio.sleep(0.5)
```

After:

```
import asyncio

async def foo():
  await ensure_future(bar())

async def bar():
  await asyncio.sleep(0.5)
```
