---
title: Informações ausentes ao usar ensure_future (Python)
type: troubleshooting
tags:
  - Agents
  - Python agent
  - Troubleshooting
metaDescription: 'If your Python application doesn''t report data after a few minutes, try these troubleshooting steps.'
freshnessValidatedDate: never
translationType: machine
---

## Problema

Informações detalhadas trace de função não aparecem ao usar `asyncio.ensure_future` em corrotinas.

## Solução

Os futuros criados a partir de `ensure_future` devem ser aguardados na mesma corrotina em que foram criados. Por exemplo, na seção <DNT>**Before**</DNT> , `await` não está presente com `ensure_future`, o que resultaria na falta de informações:

Antes:

```
import asyncio

async def foo():
  ensure_future(bar())

async def bar():
  await asyncio.sleep(0.5)
```

Depois:

```
import asyncio

async def foo():
  await ensure_future(bar())

async def bar():
  await asyncio.sleep(0.5)
```
